$ANSIBLE_VAULT;1.2;AES256;agross2
30393466393539336536343839386632313161313538616335333566346136323431373164313566
6633316332363163646538333564626133336563373339610a356164373761363035386539643734
37636639303038363230333032363933393966366561616334626439303534303132386530666334
3866363039323262640a346531393439313365643039363634323630653638366232316664326237
34343235336231313734363032616165306263303161623631303633376235383034396235653935
35353163316234333832613063623265346362396431633562643531376135336535363361663834
303132386331653230633238653535663965
