$ANSIBLE_VAULT;1.2;AES256;agross2
62383165666137363930663565366263666232306539646135306137363965353538363461373130
3531383633386230616661656536366234316438386163350a313461643530613733303936313739
61323633633434333836323266346163623937666262376631356465353636393362316436353466
3063303136633234650a656535646262333532396535616662383433363965643634373035343062
63343961386563373935316662643038646237643735376461643366353763633935383262666431
62383733396261363135623165366165653430383932656266623064646165613936646363613730
633837353763353437613134323933346566
