# renovate: github-releases=xbmc/xbmc versioning=loose
kodi_update_version: 21.3-Omega

kodi_update_version_nosuffix: >-
  {{
    kodi_update_version |
    ansible.builtin.split('-') |
    first
  }}

kodi_update_release_url: >-
  https://mirrors.kodi.tv/releases/android/arm/kodi-{{
    kodi_update_version
  }}-armeabi-v7a.apk?https=1
