$ANSIBLE_VAULT;1.2;AES256;agross2
63343038303536343339363231313161333534303436623566646130643230366636356238633538
3535653734353262383834653139343830643930623738360a346436393464326538336234313539
65653236343135353834333462383737303361663963303232656338666337346531646236333265
6336373139643964330a303164656134336338313562653139313265316437323861633139323631
63346662333833616165636231373535666430366532383364346562393866343865663930383564
31643166646266333436396362303964306234313164393834326561386538396265356162643761
663133643435663830633833386161356331
