tasmota_config_device_model: Gosund SP111

tasmota_config_template: >-
  {"NAME":"Gosund SP111 v2","GPIO":[320,0,321,0,2656,2720,0,0,2624,32,0,224,0,0],"FLAG":0,"BASE":18}

# Disable LED, but enable when there are connection issues.
tasmota_config_custom_backlog: |
  LedPower 0
  SetOption31 0
