# renovate: github-releases=arendst/Tasmota
tasmota_update_version: 15.3.0

tasmota_update_ota_release:
  tasmota: >-
    http://ota.tasmota.com/tasmota/release-{{
      tasmota_update_version
    }}/{{
      tasmota_update_ota_file | default('tasmota.bin.gz')
    }}
  tasmota32: >-
    http://ota.tasmota.com/tasmota32/release-{{
      tasmota_update_version
    }}/{{
      tasmota_update_ota_file | default('tasmota32.bin')
    }}

tasmota_update_user: admin
tasmota_update_password:

tasmota_update_credentials: >-
  {{
    '&user=' ~
    tasmota_update_user | urlencode | replace('/', '%2F') ~
    '&password=' ~
    tasmota_update_password | urlencode | replace('/', '%2F') if
      (tasmota_update_password | default('', true) | string | length) > 0
    else
      ''
  }}
