$ANSIBLE_VAULT;1.2;AES256;agross2
38353463373533363131396261653861326161303333386136613539313536663732303032386434
3765633839383761633838336237373661323537356633610a363233343361633935363763626239
38636137346330303338386633623661376133303035613430623461363633373664396233646432
3862303439626432320a656336353766663462646432353235656535356336363930633264663032
36336330363363313132613932353638616135333136373261333235323236613038393532646538
36353636326366663162303336306438623834356530643135356362303831653039626532323664
61363438323630303834613065653665396237636335326639326237623837373064343333653639
63633230653461396236653763613933623433326530353239653837386363616334336339306163
33623239633335393236653435366630633930643666366537343131393137333965663337343864
31303336633865653961346166633235653965363530313365386234613139393962306134363865
38313033396666336238343531383732343561333738313630613963333565323565623636613032
35666263373666353536633136343262663632323137346433303536613664666661316636633330
65623330666263643731653264313065356335376363653066306561343738643739393163393062
32623365323666313863613736396262663734396266353538323037653936373762336538393065
30613636646561336239303862666638303561346665376337303665363430326237383462623932
38646439656430383162
