dns_cname_records:
  - "adguard.{{ network.domain }}"
  - "dnscrypt.{{ network.domain }}"
  - "cockpit.{{ network.domain }}"

  - "{{ nextcloud_domain | mandatory }}"
  - "kibana.{{ nextcloud_domain | mandatory }}"

  - "{{ immich_domain | mandatory }}"
  - "{{ immich_mediakit_domain | mandatory }}"

  - "{{ logger_grafana_domain | ansible.builtin.mandatory }}"
  - "influxdb.{{ network.domain }}"

  - "iobroker.{{ network.domain }}"
  - "lovelace.{{ network.domain }}"
  - "telegram.{{ network.domain }}"

  - "kodi.{{ network.domain }}"

  - "{{ teamcity_domain | ansible.builtin.mandatory }}"
  - "{{ teamcity_hub_domain | ansible.builtin.mandatory }}"

  - "{{ commafeed_domain | ansible.builtin.mandatory }}"
  - "{{ feedr_domain | ansible.builtin.mandatory }}"
  - "{{ freshrss_domain | ansible.builtin.mandatory }}"
  - "{{ tandoor_domain | ansible.builtin.mandatory }}"
  - "{{ vaultwarden_domain | ansible.builtin.mandatory }}"
  - "{{ prometheus_domain | ansible.builtin.mandatory }}"

  - "{{ renovate_domain | mandatory }}"
